urllib3.connectionpool DEBUG 2024-06-10 19:23:56,565 connectionpool 3338 140162141963840 Starting new HTTPS connection (1): res.cloudinary.com:443
urllib3.connectionpool DEBUG 2024-06-10 19:23:56,638 connectionpool 3338 140162141963840 https://res.cloudinary.com:443 "GET /dddubflsq/raw/upload/v1/static/staticfiles.json HTTP/1.1" 200 None
django.request WARNING 2024-06-10 19:23:57,219 log 3338 140161157428800 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/create/styles.css.map
django.request WARNING 2024-06-10 19:24:04,712 log 3338 140161132250688 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/create/styles.css.map
django.request WARNING 2024-06-10 19:24:04,946 log 3338 140161123857984 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:24:15,604 log 3338 140161107072576 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:24:15,964 log 3338 140160620557888 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/styles.css.map
django.request WARNING 2024-06-10 19:24:20,488 log 3338 140160603772480 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/styles.css.map
django.request WARNING 2024-06-10 19:24:20,806 log 3338 140160595379776 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:37:40,409 log 3338 140160075294272 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request ERROR 2024-06-10 19:37:43,484 log 3338 140160066901568 Internal Server Error: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/django-renterprise/customers/views.py", line 43, in customer_view
    return render(
           ^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/loader_tags.py", line 208, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/defaulttags.py", line 541, in render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'customer_view_notes' with arguments '(UUID('8e05b134-0b51-46e4-ac9d-2e725f265a9b'),)' not found. 1 pattern(s) tried: ['customers/(?P<customer_token>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/customer_notes_list/(?P<id>[0-9]+)/\\Z']
django.request WARNING 2024-06-10 19:37:43,537 log 3338 140160058508864 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:37:43,783 log 3338 140160041723456 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/styles.css.map
django.request WARNING 2024-06-10 19:37:43,784 log 3338 140160050116160 Not Found: /favicon.ico
django.request WARNING 2024-06-10 19:38:17,876 log 3338 140159530030656 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/styles.css.map
django.request WARNING 2024-06-10 19:41:21,947 log 3338 140159009945152 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/styles.css.map
django.request WARNING 2024-06-10 19:45:09,598 log 3338 140158967981632 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/styles.css.map
django.request WARNING 2024-06-10 19:45:13,005 log 3338 140158473074240 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/styles.css.map
django.request WARNING 2024-06-10 19:45:13,275 log 3338 140158464681536 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request ERROR 2024-06-10 19:45:38,025 log 3338 140158456288832 Internal Server Error: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/loader_tags.py", line 208, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/defaulttags.py", line 541, in render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'customer_notes_list' with arguments '('',)' not found. 1 pattern(s) tried: ['customers/(?P<customer_token>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/customer_notes_list/\\Z']
django.request WARNING 2024-06-10 19:45:38,291 log 3338 140158447896128 Not Found: /favicon.ico
django.request WARNING 2024-06-10 19:45:38,523 log 3338 140158439503424 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:47:30,947 log 3338 140157919417920 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:47:35,423 log 3338 140157902632512 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:47:37,544 log 3338 140157885847104 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:47:38,380 log 3338 140157382547008 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/create/styles.css.map
django.request WARNING 2024-06-10 19:47:41,993 log 3338 140157365761600 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/create/styles.css.map
django.request WARNING 2024-06-10 19:47:42,307 log 3338 140157357368896 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:47:44,577 log 3338 140156862461504 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:47:44,927 log 3338 140156837283392 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/create/styles.css.map
django.request WARNING 2024-06-10 19:47:46,092 log 3338 140156820497984 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/create/styles.css.map
django.request WARNING 2024-06-10 19:47:46,412 log 3338 140156812105280 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:47:48,048 log 3338 140156317197888 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:47:48,391 log 3338 140156308805184 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/styles.css.map
django.request WARNING 2024-06-10 19:47:50,904 log 3338 140156292019776 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/styles.css.map
django.request WARNING 2024-06-10 19:47:51,126 log 3338 140156283627072 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
django.request WARNING 2024-06-10 19:47:55,264 log 3338 140155780326976 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
django.request WARNING 2024-06-10 19:47:55,482 log 3338 140155771934272 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
django.request WARNING 2024-06-10 19:48:18,833 log 3338 140155243456064 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
customers.views WARNING 2024-06-10 19:48:22,999 views 3338 140155235063360 <QuerySet [<OrderNote: OrderNote object (1)>]>
customers.views WARNING 2024-06-10 19:48:23,096 views 3338 140155235063360 <QuerySet [<OrderNote: OrderNote object (1)>]>
customers.views WARNING 2024-06-10 19:48:23,143 views 3338 140155235063360 <QuerySet [<OrderNote: OrderNote object (1)>]>
django.request WARNING 2024-06-10 19:48:23,238 log 3338 140155226670656 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
django.request WARNING 2024-06-10 19:48:23,455 log 3338 140155218277952 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/1/order_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:48:26,785 log 3338 140155201492544 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/1/order_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:48:27,001 log 3338 140154714977856 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
django.request WARNING 2024-06-10 19:49:37,759 log 3338 140154698192448 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
django.request WARNING 2024-06-10 19:49:38,071 log 3338 140154689799744 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
django.request WARNING 2024-06-10 19:49:40,070 log 3338 140154673014336 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
django.request WARNING 2024-06-10 19:49:40,238 log 3338 140154664621632 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
django.request WARNING 2024-06-10 19:51:02,665 log 3338 140154169714240 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
django.request WARNING 2024-06-10 19:51:05,408 log 3338 140154152928832 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
django.request WARNING 2024-06-10 19:51:09,954 log 3338 140154136143424 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
django.request WARNING 2024-06-10 19:52:19,995 log 3338 140153607665216 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
django.request ERROR 2024-06-10 19:52:58,650 log 3338 140153599272512 Internal Server Error: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/8/invoice_status/8/true
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: invoice_status_change() got an unexpected keyword argument 'id'
django.request WARNING 2024-06-10 19:52:58,705 log 3338 140153590879808 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
django.request WARNING 2024-06-10 19:52:58,917 log 3338 140153104365120 Not Found: /favicon.ico
django.request ERROR 2024-06-10 19:52:59,211 log 3338 140153095972416 Internal Server Error: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/8/invoice_status/8/styles.css.map
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: invoice_status_change() got an unexpected keyword argument 'id'
django.utils.autoreload INFO 2024-06-10 19:53:23,981 autoreload 3338 140162207144832 /workspace/django-renterprise/customers/urls.py changed, reloading.
django.utils.autoreload INFO 2024-06-10 19:53:24,668 autoreload 4979 139828108008320 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-06-10 19:54:04,366 autoreload 4979 139828108008320 /workspace/django-renterprise/customers/views.py changed, reloading.
django.utils.autoreload INFO 2024-06-10 19:54:05,276 autoreload 5024 140355317447552 Watching for file changes with StatReloader
django.request WARNING 2024-06-10 19:54:07,544 log 5024 140355169154624 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
django.request ERROR 2024-06-10 19:54:07,610 log 5024 140355252266560 Internal Server Error: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/8/invoice_status/8/styles.css.map
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/django-renterprise/customers/views.py", line 241, in invoice_status_change
    return redirect('customers:customer_order_view',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'customer_order_view' with keyword arguments '{'customer_token': UUID('8e05b134-0b51-46e4-ac9d-2e725f265a9b'), 'order_id': 8}' not found. 1 pattern(s) tried: ['customers/(?P<customer_token>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/orders/(?P<id>[0-9]+)\\Z']
urllib3.connectionpool DEBUG 2024-06-10 19:54:08,536 connectionpool 5024 140355160761920 Starting new HTTPS connection (1): res.cloudinary.com:443
urllib3.connectionpool DEBUG 2024-06-10 19:54:08,601 connectionpool 5024 140355160761920 https://res.cloudinary.com:443 "GET /dddubflsq/raw/upload/v1/static/staticfiles.json HTTP/1.1" 200 None
django.request WARNING 2024-06-10 19:54:09,333 log 5024 140355118798400 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
django.request ERROR 2024-06-10 19:54:13,323 log 5024 140354565174848 Internal Server Error: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/8/invoice_status/8/false
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/django-renterprise/customers/views.py", line 241, in invoice_status_change
    return redirect('customers:customer_order_view',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'customer_order_view' with keyword arguments '{'customer_token': UUID('8e05b134-0b51-46e4-ac9d-2e725f265a9b'), 'order_id': 8}' not found. 1 pattern(s) tried: ['customers/(?P<customer_token>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/orders/(?P<id>[0-9]+)\\Z']
django.request WARNING 2024-06-10 19:54:13,377 log 5024 140354556782144 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
django.request WARNING 2024-06-10 19:54:13,594 log 5024 140354548389440 Not Found: /favicon.ico
django.request ERROR 2024-06-10 19:54:13,901 log 5024 140354539996736 Internal Server Error: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/8/invoice_status/8/styles.css.map
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/django-renterprise/customers/views.py", line 241, in invoice_status_change
    return redirect('customers:customer_order_view',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'customer_order_view' with keyword arguments '{'customer_token': UUID('8e05b134-0b51-46e4-ac9d-2e725f265a9b'), 'order_id': 8}' not found. 1 pattern(s) tried: ['customers/(?P<customer_token>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/orders/(?P<id>[0-9]+)\\Z']
django.request ERROR 2024-06-10 19:54:22,509 log 5024 140354523211328 Internal Server Error: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/8/invoice_status/8/styles.css.map
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/django-renterprise/customers/views.py", line 241, in invoice_status_change
    return redirect('customers:customer_order_view',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/shortcuts.py", line 48, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/shortcuts.py", line 145, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'customer_order_view' with keyword arguments '{'customer_token': UUID('8e05b134-0b51-46e4-ac9d-2e725f265a9b'), 'order_id': 8}' not found. 1 pattern(s) tried: ['customers/(?P<customer_token>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/orders/(?P<id>[0-9]+)\\Z']
django.request WARNING 2024-06-10 19:54:22,558 log 5024 140354514818624 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
django.request WARNING 2024-06-10 19:54:25,612 log 5024 140353986340416 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
django.utils.autoreload INFO 2024-06-10 19:55:06,286 autoreload 5024 140355317447552 /workspace/django-renterprise/customers/urls.py changed, reloading.
django.utils.autoreload INFO 2024-06-10 19:55:06,947 autoreload 5107 139626366385024 Watching for file changes with StatReloader
django.utils.autoreload INFO 2024-06-10 19:56:33,874 autoreload 5107 139626366385024 /workspace/django-renterprise/orders/views.py changed, reloading.
django.utils.autoreload INFO 2024-06-10 19:56:34,525 autoreload 5237 139767496924032 Watching for file changes with StatReloader
django.request ERROR 2024-06-10 19:56:43,214 log 5237 139767362614848 Internal Server Error: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/8
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: customer_order_view() got an unexpected keyword argument 'order_id'
django.request WARNING 2024-06-10 19:56:43,404 log 5237 139767354222144 Not Found: /favicon.ico
django.request WARNING 2024-06-10 19:56:43,589 log 5237 139767345829440 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
django.utils.autoreload INFO 2024-06-10 19:57:06,051 autoreload 5237 139767496924032 /workspace/django-renterprise/customers/views.py changed, reloading.
django.utils.autoreload INFO 2024-06-10 19:57:06,731 autoreload 5287 139946002451328 Watching for file changes with StatReloader
urllib3.connectionpool DEBUG 2024-06-10 19:57:09,742 connectionpool 5287 139945870095936 Starting new HTTPS connection (1): res.cloudinary.com:443
urllib3.connectionpool DEBUG 2024-06-10 19:57:09,818 connectionpool 5287 139945870095936 https://res.cloudinary.com:443 "GET /dddubflsq/raw/upload/v1/static/staticfiles.json HTTP/1.1" 200 None
django.request WARNING 2024-06-10 19:57:10,215 log 5287 139945827067456 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
django.request WARNING 2024-06-10 19:57:14,196 log 5287 139945326929472 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
django.request WARNING 2024-06-10 19:57:28,286 log 5287 139945310144064 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
django.request WARNING 2024-06-10 19:57:28,659 log 5287 139945301751360 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/styles.css.map
django.request WARNING 2024-06-10 19:57:29,998 log 5287 139945284965952 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/styles.css.map
django.request WARNING 2024-06-10 19:57:30,223 log 5287 139944798451264 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:57:31,435 log 5287 139944781665856 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:57:31,749 log 5287 139944773273152 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/styles.css.map
django.request WARNING 2024-06-10 19:57:32,592 log 5287 139944756487744 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/styles.css.map
django.request WARNING 2024-06-10 19:57:32,827 log 5287 139944748095040 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:57:34,198 log 5287 139944244794944 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:57:34,523 log 5287 139944228009536 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/create/styles.css.map
django.request WARNING 2024-06-10 19:57:38,950 log 5287 139943724709440 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/create/styles.css.map
django.request WARNING 2024-06-10 19:57:39,168 log 5287 139943716316736 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:57:41,039 log 5287 139943699531328 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:57:41,377 log 5287 139943674353216 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/108/styles.css.map
django.request WARNING 2024-06-10 19:57:52,466 log 5287 139943171053120 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/108/styles.css.map
django.request WARNING 2024-06-10 19:57:52,793 log 5287 139943162660416 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:58:11,972 log 5287 139943145875008 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:58:11,987 log 5287 139943137482304 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/styles.css.map
django.request WARNING 2024-06-10 19:58:12,949 log 5287 139942642574912 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/styles.css.map
django.request WARNING 2024-06-10 19:58:13,263 log 5287 139942634182208 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:58:15,862 log 5287 139942609004096 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:58:16,202 log 5287 139942114096704 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/create/styles.css.map
django.request WARNING 2024-06-10 19:58:17,408 log 5287 139942097311296 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/create/styles.css.map
django.request WARNING 2024-06-10 19:58:17,626 log 5287 139942088918592 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:58:34,634 log 5287 139941568833088 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:58:37,494 log 5287 139941552047680 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/customer_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:58:37,735 log 5287 139941543654976 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/styles.css.map
django.request WARNING 2024-06-10 19:58:41,073 log 5287 139941526869568 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/styles.css.map
django.request WARNING 2024-06-10 19:58:41,299 log 5287 139941040354880 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
django.request WARNING 2024-06-10 19:58:42,791 log 5287 139941023569472 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
django.request WARNING 2024-06-10 19:58:42,998 log 5287 139941015176768 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
customers.views WARNING 2024-06-10 19:58:45,900 views 5287 139941006784064 <QuerySet [<OrderNote: OrderNote object (1)>]>
customers.views WARNING 2024-06-10 19:58:46,000 views 5287 139941006784064 <QuerySet [<OrderNote: OrderNote object (1)>]>
customers.views WARNING 2024-06-10 19:58:46,040 views 5287 139941006784064 <QuerySet [<OrderNote: OrderNote object (1)>]>
django.request WARNING 2024-06-10 19:58:46,149 log 5287 139940998391360 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/styles.css.map
django.request WARNING 2024-06-10 19:58:46,363 log 5287 139940989998656 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/1/order_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:58:48,744 log 5287 139940486698560 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/1/order_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:58:49,180 log 5287 139940469913152 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/1/order_notes_list/styles.css.map
customers.views WARNING 2024-06-10 19:58:54,770 views 5287 139940453127744 <QuerySet [<OrderNote: OrderNote object (1)>]>
customers.views WARNING 2024-06-10 19:58:54,871 views 5287 139940453127744 <QuerySet [<OrderNote: OrderNote object (1)>]>
customers.views WARNING 2024-06-10 19:58:54,912 views 5287 139940453127744 <QuerySet [<OrderNote: OrderNote object (1)>]>
django.request WARNING 2024-06-10 19:58:55,004 log 5287 139939966613056 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/1/order_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:58:55,320 log 5287 139939958220352 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/1/order_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:58:58,059 log 5287 139939933042240 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/1/order_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:58:58,477 log 5287 139939916256832 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/1/order_notes_list/create/styles.css.map
customers.views WARNING 2024-06-10 19:59:07,060 views 5287 139939421349440 <QuerySet [<OrderNote: OrderNote object (1)>, <OrderNote: OrderNote object (11)>]>
customers.views WARNING 2024-06-10 19:59:07,149 views 5287 139939421349440 <QuerySet [<OrderNote: OrderNote object (1)>, <OrderNote: OrderNote object (11)>]>
customers.views WARNING 2024-06-10 19:59:07,190 views 5287 139939421349440 <QuerySet [<OrderNote: OrderNote object (1)>, <OrderNote: OrderNote object (11)>]>
django.request WARNING 2024-06-10 19:59:07,294 log 5287 139939412956736 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/1/order_notes_list/create/styles.css.map
django.request WARNING 2024-06-10 19:59:07,620 log 5287 139939404564032 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/1/order_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:59:11,587 log 5287 139939379385920 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/1/order_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:59:11,899 log 5287 139938884478528 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/1/order_notes_list/styles.css.map
customers.views WARNING 2024-06-10 19:59:18,295 views 5287 139938876085824 <QuerySet [<OrderNote: OrderNote object (1)>, <OrderNote: OrderNote object (11)>]>
customers.views WARNING 2024-06-10 19:59:18,391 views 5287 139938876085824 <QuerySet [<OrderNote: OrderNote object (1)>, <OrderNote: OrderNote object (11)>]>
customers.views WARNING 2024-06-10 19:59:18,434 views 5287 139938876085824 <QuerySet [<OrderNote: OrderNote object (1)>, <OrderNote: OrderNote object (11)>]>
django.request WARNING 2024-06-10 19:59:18,558 log 5287 139938867693120 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/1/order_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:59:18,880 log 5287 139938859300416 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/1/order_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:59:20,403 log 5287 139938356000320 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/1/order_notes_list/styles.css.map
django.request WARNING 2024-06-10 19:59:21,271 log 5287 139938339214912 Not Found: /customers/8e05b134-0b51-46e4-ac9d-2e725f265a9b/orders/1/order_notes_list/create/styles.css.map
